# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-dwh
      user: dbt
      password: dbt
      port: 5432
      dbname: jaffle_shop
      schema: dbt_alice
      threads: 4
